trigger:
  branches:
    include:
      - azure-pipeline-test-2
    exclude:
      - develop
# variables:
#   - group: FTSKeys


jobs:
- template: Templates/build-ipa.yml
  parameters:
    job_name: ExampleA_Release
    variables: 'ExampleAKeys'
    app_name: ExampleA

- template: Templates/build-ipa.yml
  parameters:
    job_name: ExampleB_Release
    variables: 'ExampleBKeys'
    app_name: ExampleB

- template: Templates/build-ipa.yml
  parameters:
    job_name: ExampleC_Release
    variables: 'ExampleCKeys'
    app_name: ExampleC