trigger:
  branches:
    include:
      - azure-pipeline-yaml
    exclude:
      - develop

jobs: 

- job: iOS_Release
  pool:
    vmImage: 'macOS-latest'
  variables:
    - group: FTSKeys
  condition: succeeded()
  strategy:
    maxParallel: 16
    matrix:
      ExampleA:
        app_name: "ExampleA"
        variables: 
          group: ExampleAKeys
      ExampleB:
        app_name: "ExampleB"
      ExampleC:
        app_name: "ExampleC"
  steps:
    - script: gem install bundler
    - script: bundle install
    - script: echo $key1
    # - script: fastlane ios_appstore_no_upload app_name:$(app_name) build_number:2
    - script: fastlane build app_name:$(app_name) build_number:2
      env:
          DIST_P12_PASSWORD: $(DIST_P12_PASSWORD)
    - publish: $(System.DefaultWorkingDirectory)/artifacts/builds/appstore
      artifact: "$(app_name)"