trigger:
  branches:
    include:
      - azure-pipeline-test-2
    exclude:
      - develop
variables:
  - group: FTSKeys


jobs:
- template: build.yml  # Template reference
  parameters:
    job_name: iOS_Release
    pool:
      vmImage: 'macOS-10.14'
    variable_group_name:
      group: ExampleAKeys
    app_name: ExampleA