trigger:
  - azure-pipeline-yaml

jobs: 

- job: iOS_Release
  pool:
    vmImage: 'macOS-latest'
  variables:
    group: FTSKeys
  condition: succeeded()
  strategy:
    matrix:
      ExampleA:
        app_name: "ExampleA"
      # ExampleB:
      #   app_name: "ExampleB"
      # ExampleC:
      #   app_name: "ExampleC"
  steps:
    - script: gem install bundler
    - script: bundle install
    - script: export DIST_P12_PASSWORD=$(DIST_P12_PASSWORD)
    - script: fastlane ios_appstore_no_upload app_name:$(app_name) build_number:2