parameters:
  job_name: ''
  app_name: ''
  pool: ''
  variable_group_name: ''

jobs:
- job: ${{ parameters.job_name }}
  pool: ${{ parameters.pool }}
  condition: succeeded()
  variables: ${{ parameters.variable_group_name }}
  steps:
    - script: gem install bundler
    - script: bundle install
    - script: echo $key1
    - script: fastlane build app_name:${{ parameters.app_name }} build_number:2
      env:
          DIST_P12_PASSWORD: $(DIST_P12_PASSWORD)
    - publish: $(System.DefaultWorkingDirectory)/artifacts/builds/appstore
      artifact: ${{ parameters.app_name }}